backend:
  name: github
  repo: "JuanBarreiroSanroman/Repositorio_Hugo_Decap"  # Reemplaza con tu usuario y nombre del repositorio
  branch: main  # O la rama que estés usando, como "master"
  auth_scope: "repo"  # Esto otorga acceso completo a tu repositorio
  api_root: "https://api.github.com"  # Si es necesario especificar la URL API
  token: "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"  # Deberás crear un token de acceso personal en GitHub (ver paso 2)


media_folder: "static/images/uploads" # Carpeta donde se guardarán las imágenes
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
